title: Dalton Facer
description: This portfolio showcases the work of Dalton Facer, an undergraduate student in the College of Engineering at the University of Delaware.
logo: 5.jpg
theme: jekyll-theme-slate
