title: Dalton Facer
description: This portfolio showcases the work of Dalton Facer, an undergraduate student in the College of Engineering at the University of Delaware. Here, Dalton highlights his most ambitious and professional engineering designs and projects.
theme: jekyll-theme-slate
